// Product data for Convoltaje and Tintaflash

export interface Product {
  id: string;
  name: string;
  description: string;
  price: number;
  image: string;
  category: string;
  popular?: boolean;
  discount?: number;
}

export const CONVOLTAJE_PRODUCTS: Product[] = [
  {
    id: "conv-1",
    name: "Sistema 6K PLUS",
    description: "Ideal para Aire Acondicionado y el resto de la casa. Incluye 8 Paneles Solares, 6kw de Inversor MUST y 15KW de Batería Lifepop4 MUST",
    price: 6950,
    image: "https://img2.elyerromenu.com/images/convoltaje/sistema-6k-plus/img-s.webp",
    category: "Sistemas Solares Completos",
    discount: 7,
  },
  {
    id: "conv-2",
    name: "Sistema Básico - 1500W",
    description: "Tu primer paso para dejar los apagones. Sistema completamente 110v, ideal para quienes quieren comenzar a vivir con energía limpia.",
    price: 1745,
    image: "https://img2.elyerromenu.com/images/convoltaje/sistema-solar-basicos-1200w-p/img-m.webp",
    category: "Sistemas Solares Completos",
    popular: true,
    discount: 11,
  },
  {
    id: "conv-3",
    name: "Sistema Solar - Medio 3000W",
    description: "Más potencia, más comodidad. Pensado para hogares que necesitan algo más.",
    price: 2750,
    image: "https://img2.elyerromenu.com/images/convoltaje/sistema-solar-medio-3000w-5o5/img-s.webp",
    category: "Sistemas Solares Completos",
    popular: true,
    discount: 10,
  },
  {
    id: "conv-4",
    name: "Sistema Solar Aire Acondicionado 3000W",
    description: "Ideal para hogares completos. Ofrece corriente 110V y 220V simultáneos.",
    price: 3950,
    image: "https://img2.elyerromenu.com/images/convoltaje/sistema-solar-aire-acondicionado-gg1/img-s.webp",
    category: "Sistemas Solares Completos",
    popular: true,
    discount: 11,
  },
  {
    id: "conv-5",
    name: "Sistema Avanzado 6000W",
    description: "Pensado para quienes no quieren límites. Diseñado para hogares grandes o pequeños negocios.",
    price: 5950,
    image: "https://img2.elyerromenu.com/images/convoltaje/sistema-avanzado-5000w-ofo/img-s.webp",
    category: "Sistemas Solares Completos",
    popular: true,
    discount: 13,
  },
  {
    id: "conv-6",
    name: "Sistema Premium 10000W",
    description: "ConVoltaje: solución definitiva. El tope de gama con 12 paneles solares y gran banco de baterías.",
    price: 9850,
    image: "https://img2.elyerromenu.com/images/convoltaje/sistema-premium-10000w-1wr/img-s.webp",
    category: "Sistemas Solares Completos",
    popular: true,
    discount: 12,
  },
  {
    id: "conv-11",
    name: "Sistema Híbrido 5000W",
    description: "Solución híbrida versátil para integrar energía solar y la red eléctrica de forma eficiente.",
    price: 4950,
    image: "",
    category: "Sistemas Solares Completos",
    popular: true,
  },
  {
    id: "conv-12",
    name: "Sistema Básico Plus",
    description: "Ideal para iniciar con más capacidad que el sistema básico, permitiendo refrigeración y luces.",
    price: 2150,
    image: "https://img2.elyerromenu.com/images/convoltaje/sistema-basico-plus-u-18e/img.webp",
    category: "Sistemas Solares Completos",
  },
  {
    id: "conv-7",
    name: "EcoFlow DELTA 2",
    description: "Capacidad: 1024 Wh. Potencia: 1800 W. Recarga rápida: 0-80% en 50 minutos.",
    price: 950,
    image: "https://img2.elyerromenu.com/images/convoltaje/ecoflow-delta-2-estacion-de-energia-portatil-inteligente/img-s.webp",
    category: "PowerStations",
    popular: true,
    discount: 14,
  },
  {
    id: "conv-8",
    name: "EcoFlow DELTA 2 Max",
    description: "Capacidad: 2048 Wh. Potencia: 2400 W. Ideal para respaldo del hogar.",
    price: 1800,
    image: "https://img2.elyerromenu.com/images/convoltaje/ecoflow-delta-2-max-estacion-de-energia-de-alta-capacidad/img-s.webp",
    category: "PowerStations",
    popular: true,
  },
  {
    id: "conv-9",
    name: "Bluetti AC200P",
    description: "Capacidad: 2000 Wh. Potencia: 2000 W. Pantalla táctil intuitiva.",
    price: 860,
    image: "https://img2.elyerromenu.com/images/convoltaje/bluetti-ac200p/img-s.webp",
    category: "PowerStations",
    discount: 9,
  },
  {
    id: "conv-10",
    name: "Anker Solix F2000",
    description: "Capacidad: 2048 Wh. Potencia: 2300 W. Recarga 0-80% en 1.4 horas.",
    price: 1100,
    image: "https://img2.elyerromenu.com/images/convoltaje/anker-solix-f2000/img-s.webp",
    category: "PowerStations",
  },
  {
    id: "conv-13",
    name: "EcoFlow RIVER 2",
    description: "Capacidad: 256 Wh. Potencia: 300 W (X-Boost 600 W). Ultra portátil y carga rápida en 1 hora.",
    price: 290,
    image: "https://img2.elyerromenu.com/images/convoltaje/ecoflow-river-2-p/img.webp",
    category: "PowerStations",
    popular: true,
  },
  {
    id: "conv-14",
    name: "Panel Solar 550W Monocristalino",
    description: "Panel solar de alta eficiencia para expansiones o instalaciones personalizadas.",
    price: 180,
    image: "https://img2.elyerromenu.com/images/convoltaje/panel-solar-550w/img-s.webp",
    category: "Insumos Individuales",
  },
  {
    id: "conv-15",
    name: "Inversor MUST Híbrido 3KW",
    description: "Inversor cargador MUST para sistemas aislados o híbridos a 110V/220V.",
    price: 450,
    image: "https://img2.elyerromenu.com/images/convoltaje/inversor-must-3kw/img-s.webp",
    category: "Insumos Individuales",
  },
  {
    id: "conv-16",
    name: "Batería Litio LiFePO4 5.1kWh",
    description: "Batería de larga vida útil (más de 6000 ciclos) y máxima seguridad.",
    price: 1200,
    image: "https://img2.elyerromenu.com/images/convoltaje/bateria-litio-5kwh/img-s.webp",
    category: "Insumos Individuales",
  },
];

export const TINTAFLASH_PRODUCTS: Product[] = [
  {
    id: "tinta-1",
    name: "Púlover de Niño",
    description: "Haz que los pequeños brillen con nuestros púloveres personalizables. Diseña el tuyo con colores, nombres o divertidos gráficos.",
    price: 1800,
    image: "https://img1.elyerromenu.com/images/tintaflash/pulover-de-nino-x/img-s.webp",
    category: "Ropa Personalizada",
  },
  {
    id: "tinta-2",
    name: "Mousepad",
    description: "Transforma tu espacio de trabajo con nuestros mousepads personalizables.",
    price: 600,
    image: "https://img1.elyerromenu.com/images/tintaflash/mousepad-k/img-s.webp",
    category: "Accesorios",
    popular: true,
  },
  {
    id: "tinta-3",
    name: "Billeteras Personalizadas para Papá",
    description: "Sorprende a papá con una billetera única. Personalízala con su foto favorita.",
    price: 2600,
    image: "https://img1.elyerromenu.com/images/tintaflash/billeteras-personalizadas-para-papa-c/img-m.webp",
    category: "Regalos",
    popular: true,
  },
  {
    id: "tinta-4",
    name: "Bolsas de Regalo Variadas",
    description: "El toque perfecto para cualquier ocasión especial. Modelos con brillo, estampados elegantes y temáticos.",
    price: 500,
    image: "https://img1.elyerromenu.com/images/tintaflash/bolsas-de-regalo-variadas/img-s.webp",
    category: "Regalos",
  },
  {
    id: "tinta-5",
    name: "Ropa Interior Masculina",
    description: "Personaliza tus boxers con el diseño que más te guste. Tallas L y M disponibles.",
    price: 1900,
    image: "https://img1.elyerromenu.com/images/tintaflash/ropa-interior-masculina-8/img-m.webp",
    category: "Ropa Personalizada",
  },
  {
    id: "tinta-6",
    name: "Tazas Personalizadas",
    description: "Una taza sublimada de cerámica personalizada. Acabado de alta calidad y duradero.",
    price: 1800,
    image: "https://img1.elyerromenu.com/images/tintaflash/tazas-personalizadas-3/img-m.webp",
    category: "Hogar",
    popular: true,
  },
  {
    id: "tinta-7",
    name: "Pulóvers Personalizados",
    description: "Luce tu estilo único con nuestros púloveres blancos personalizables.",
    price: 1800,
    image: "https://img1.elyerromenu.com/images/tintaflash/pulovers-personalizados-6/img-m.webp",
    category: "Ropa Personalizada",
    popular: true,
  },
  {
    id: "tinta-8",
    name: "Llaveros de MDF",
    description: "Añade un toque personal a tus llaves con nuestros llaveros personalizables.",
    price: 400,
    image: "https://img1.elyerromenu.com/images/tintaflash/llaveros-de-mdf/img-s.webp",
    category: "Accesorios",
  },
  {
    id: "tinta-9",
    name: "Jarras Térmicas Personalizadas",
    description: "Mantén tus bebidas a la temperatura perfecta con nuestras jarras térmicas personalizables.",
    price: 3600,
    image: "https://img1.elyerromenu.com/images/tintaflash/jarras-termicas-personalizadas-j/img-s.webp",
    category: "Hogar",
  },
  {
    id: "tinta-10",
    name: "Cuadros de PVC",
    description: "Transforma tus espacios con nuestros cuadros de PVC personalizables.",
    price: 1800,
    image: "https://img1.elyerromenu.com/images/tintaflash/cuadros-de-pvc/img-m.webp",
    category: "Decoración",
    popular: true,
  },
  {
    id: "tinta-11",
    name: "Cojines Personalizados",
    description: "Añade un toque especial a tu hogar con nuestros cojines personalizables.",
    price: 1500,
    image: "https://img1.elyerromenu.com/images/tintaflash/cojines-personalizados-5/img-s.webp",
    category: "Hogar",
  },
  {
    id: "tinta-12",
    name: "Pomos Metálicos",
    description: "Descubre nuestros pomos metálicos de 750 ml. Diseña el tuyo con nombres, frases o imágenes.",
    price: 2600,
    image: "https://img1.elyerromenu.com/images/tintaflash/pomos-metalicos-9/img-s.webp",
    category: "Hogar",
    popular: true,
  },
];

export const WHATSAPP_NUMBERS = {
  convoltaje: "+5355507913",
  tintaflash: "+5355507913",
};

export const CONTACT_INFO = {
  email: "convoltaje@gmail.com",
  instagram: "https://www.instagram.com/convoltajecuba",
  facebook: "https://www.facebook.com/convoltajecuba",
  youtube: "https://www.youtube.com/@convoltajecuba",
  tiktok: "https://www.tiktok.com/@convoltaje",
};
